// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skjwksjurtpehixfochg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrandrc2p1cnRwZWhpeGZvY2hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MjY3MDMsImV4cCI6MjA2MTUwMjcwM30.CsvwWgIDG3fELgZwPfhTNMtEe6snc6y1tR6BPtm8bKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);